### ISSUE TITLE
Many times Shrinking operation is not reducing latency, Bound_clip issue? 

### ISSUE THREAD

**Issue by soyebn** [AberHu/TF-NAS#4]
Hi AberHu,

With your suggestions now I am able to use train_search w/o SE and w/o swish. Thanks again.

I noticed for lower target latency, many times Shrinking operation is not reducing latency. Due to that latency after search is not close to target latency. One such example below,

_Now shrinking or expanding the arch
Before, the current lat: 161.7280, the target lat: 146.0000
Shrinking......
After, the current lat: 161.7280, the target lat: 146.0000
epoch: 43 lr: 1.295099e-02 T: 1.299932e+00_

I did little debugging, realized the following could be reason for the same.
def bound_clip(mc_num, max_mc_num):
	min_mc_num = max_mc_num // 2
Can I set this to some lower bound like the following?
 	min_mc_num = max_mc_num // 4.

Will it have any adverse side effects?

Thanks again for your help.

**Comment by abhishekaich27** [comment]
@soyebn did your change work?
